"""initial_schema

Revision ID: 50b84530c27a
Revises: 
Create Date: 2026-05-18 08:39:35.222025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50b84530c27a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counties',
    sa.Column('rc_code', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('rc_code')
    )
    op.create_table('technology_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('public_name', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'editor', 'viewer')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX idx_audit_log_at ON audit_log(at DESC)")
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_log_user', 'audit_log', ['user_id'], unique=False)
    op.create_table('bulk_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.Text(), nullable=False),
    sa.Column('filter_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_count', sa.Integer(), nullable=False),
    sa.Column('rollback_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('rolled_back_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX idx_bulk_operations_created ON bulk_operations(created_at DESC)")
    op.create_index('idx_bulk_operations_user', 'bulk_operations', ['user_id'], unique=False)
    op.create_table('municipalities',
    sa.Column('rc_code', sa.Integer(), nullable=False),
    sa.Column('county_code', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['county_code'], ['counties.rc_code'], ),
    sa.PrimaryKeyConstraint('rc_code')
    )
    op.create_index('idx_municipalities_county', 'municipalities', ['county_code'], unique=False)
    op.create_geospatial_table('service_zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('polygon', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_service_zones_polygon', 'service_zones', ['polygon'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('technologies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type_id', sa.Uuid(), nullable=False),
    sa.Column('variant_code', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('theoretical_max_dl_mbps', sa.Integer(), nullable=True),
    sa.Column('theoretical_max_ul_mbps', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['technology_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_code')
    )
    op.create_index('idx_technologies_type', 'technologies', ['type_id'], unique=False)
    op.create_geospatial_table('localities',
    sa.Column('rc_code', sa.Integer(), nullable=False),
    sa.Column('muni_code', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('boundary', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('synced_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['muni_code'], ['municipalities.rc_code'], ),
    sa.PrimaryKeyConstraint('rc_code')
    )
    op.create_geospatial_index('idx_localities_boundary', 'localities', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('idx_localities_muni', 'localities', ['muni_code'], unique=False)
    op.create_table('zone_offerings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('technology_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('max_download_mbps', sa.Integer(), nullable=False),
    sa.Column('max_upload_mbps', sa.Integer(), nullable=False),
    sa.Column('status_since', sa.Date(), nullable=False),
    sa.Column('planned_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.CheckConstraint("status IN ('available', 'planned', 'under_construction', 'unavailable')", name='ck_zone_offerings_status'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['service_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'technology_id')
    )
    op.create_index('idx_zone_offerings_status', 'zone_offerings', ['status'], unique=False)
    op.create_index('idx_zone_offerings_tech', 'zone_offerings', ['technology_id'], unique=False)
    op.create_index('idx_zone_offerings_zone', 'zone_offerings', ['zone_id'], unique=False)
    op.create_geospatial_table('streets',
    sa.Column('rc_code', sa.Integer(), nullable=False),
    sa.Column('locality_code', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('axis', Geometry(geometry_type='MULTILINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('synced_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['locality_code'], ['localities.rc_code'], ),
    sa.PrimaryKeyConstraint('rc_code')
    )
    op.create_geospatial_index('idx_streets_axis', 'streets', ['axis'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('idx_streets_locality', 'streets', ['locality_code'], unique=False)
    op.create_geospatial_table('addresses',
    sa.Column('rc_code', sa.BigInteger(), nullable=False),
    sa.Column('street_code', sa.Integer(), nullable=True),
    sa.Column('locality_code', sa.Integer(), nullable=False),
    sa.Column('house_no', sa.Text(), nullable=False),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('point', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('synced_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['locality_code'], ['localities.rc_code'], ),
    sa.ForeignKeyConstraint(['street_code'], ['streets.rc_code'], ),
    sa.PrimaryKeyConstraint('rc_code')
    )
    op.create_geospatial_index('idx_addresses_point', 'addresses', ['point'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('address_offerings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('address_code', sa.BigInteger(), nullable=False),
    sa.Column('technology_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('max_download_mbps', sa.Integer(), nullable=False),
    sa.Column('max_upload_mbps', sa.Integer(), nullable=False),
    sa.Column('status_since', sa.Date(), nullable=False),
    sa.Column('planned_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('bulk_operation_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.CheckConstraint("status IN ('available', 'planned', 'under_construction', 'unavailable')", name='ck_address_offerings_status'),
    sa.ForeignKeyConstraint(['address_code'], ['addresses.rc_code'], ),
    sa.ForeignKeyConstraint(['bulk_operation_id'], ['bulk_operations.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address_code', 'technology_id')
    )
    op.create_index('idx_address_offerings_addr', 'address_offerings', ['address_code'], unique=False)
    op.create_index('idx_address_offerings_bulk', 'address_offerings', ['bulk_operation_id'], unique=False)
    op.create_index('idx_address_offerings_status', 'address_offerings', ['status'], unique=False)
    op.create_index('idx_address_offerings_tech', 'address_offerings', ['technology_id'], unique=False)
    # ### end Alembic commands ###

    # GIN trigram indexes (full-text search)
    op.create_index('idx_localities_name_trgm', 'localities', ['name'],
        postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('idx_streets_full_name_trgm', 'streets', ['full_name'],
        postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_index('idx_addresses_house_no_trgm', 'addresses', ['house_no'],
        postgresql_using='gin', postgresql_ops={'house_no': 'gin_trgm_ops'})

    # Partial indexes
    op.create_index('idx_addresses_street', 'addresses', ['street_code'],
        postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_addresses_locality', 'addresses', ['locality_code'],
        postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_api_keys_user', 'api_keys', ['user_id'],
        postgresql_where=sa.text('revoked_at IS NULL'))

    # Seed data
    import uuid
    technology_types = sa.table('technology_types',
        sa.column('id', sa.Uuid),
        sa.column('code', sa.Text),
        sa.column('display_name', sa.Text),
        sa.column('public_name', sa.Text),
        sa.column('sort_order', sa.Integer),
        sa.column('active', sa.Boolean),
    )
    fiber_id    = uuid.uuid4()
    eth_id      = uuid.uuid4()
    wireless_id = uuid.uuid4()
    lte_id      = uuid.uuid4()
    op.bulk_insert(technology_types, [
        {'id': fiber_id,    'code': 'FIBER',    'display_name': 'Šviesolaidis', 'public_name': 'Šviesolaidis',       'sort_order': 10, 'active': True},
        {'id': eth_id,      'code': 'ETHERNET', 'display_name': 'Ethernet',     'public_name': 'Ethernet',           'sort_order': 20, 'active': True},
        {'id': wireless_id, 'code': 'WIRELESS', 'display_name': 'Bevielis',     'public_name': 'Bevielis',           'sort_order': 30, 'active': True},
        {'id': lte_id,      'code': 'LTE',      'display_name': 'LTE',          'public_name': 'Mobilus internetas', 'sort_order': 40, 'active': True},
    ])

    technologies = sa.table('technologies',
        sa.column('id', sa.Uuid),
        sa.column('type_id', sa.Uuid),
        sa.column('variant_code', sa.Text),
        sa.column('display_name', sa.Text),
        sa.column('theoretical_max_dl_mbps', sa.Integer),
        sa.column('theoretical_max_ul_mbps', sa.Integer),
        sa.column('sort_order', sa.Integer),
        sa.column('active', sa.Boolean),
    )
    op.bulk_insert(technologies, [
        {'id': uuid.uuid4(), 'type_id': fiber_id,    'variant_code': 'gpon',      'display_name': 'Šviesolaidis GPON',  'theoretical_max_dl_mbps': 2500,  'theoretical_max_ul_mbps': 1250,  'sort_order': 10, 'active': True},
        {'id': uuid.uuid4(), 'type_id': fiber_id,    'variant_code': 'xgpon',     'display_name': 'Šviesolaidis XGPON', 'theoretical_max_dl_mbps': 10000, 'theoretical_max_ul_mbps': 10000, 'sort_order': 11, 'active': True},
        {'id': uuid.uuid4(), 'type_id': eth_id,      'variant_code': 'fttb_utp',  'display_name': 'Ethernet (FTTB)',    'theoretical_max_dl_mbps': 1000,  'theoretical_max_ul_mbps': 1000,  'sort_order': 20, 'active': True},
        {'id': uuid.uuid4(), 'type_id': wireless_id, 'variant_code': 'p2mp_5ghz', 'display_name': 'Bevielis 5GHz P2MP', 'theoretical_max_dl_mbps': 200,   'theoretical_max_ul_mbps': 100,   'sort_order': 30, 'active': True},
        {'id': uuid.uuid4(), 'type_id': wireless_id, 'variant_code': 'p2p_5ghz',  'display_name': 'Bevielis 5GHz P2P',  'theoretical_max_dl_mbps': 500,   'theoretical_max_ul_mbps': 250,   'sort_order': 31, 'active': True},
        {'id': uuid.uuid4(), 'type_id': lte_id,      'variant_code': '4g_lte',    'display_name': 'LTE 4G',             'theoretical_max_dl_mbps': 150,   'theoretical_max_ul_mbps': 50,    'sort_order': 40, 'active': True},
        {'id': uuid.uuid4(), 'type_id': lte_id,      'variant_code': '5g_nr',     'display_name': 'LTE 5G',             'theoretical_max_dl_mbps': 1000,  'theoretical_max_ul_mbps': 100,   'sort_order': 41, 'active': True},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_address_offerings_tech', table_name='address_offerings')
    op.drop_index('idx_address_offerings_status', table_name='address_offerings')
    op.drop_index('idx_address_offerings_bulk', table_name='address_offerings')
    op.drop_index('idx_address_offerings_addr', table_name='address_offerings')
    op.drop_table('address_offerings')
    op.drop_geospatial_index('idx_addresses_point', table_name='addresses', postgresql_using='gist', column_name='point')
    op.drop_geospatial_table('addresses')
    op.drop_index('idx_streets_locality', table_name='streets')
    op.drop_geospatial_index('idx_streets_axis', table_name='streets', postgresql_using='gist', column_name='axis')
    op.drop_geospatial_table('streets')
    op.drop_index('idx_zone_offerings_zone', table_name='zone_offerings')
    op.drop_index('idx_zone_offerings_tech', table_name='zone_offerings')
    op.drop_index('idx_zone_offerings_status', table_name='zone_offerings')
    op.drop_table('zone_offerings')
    op.drop_index('idx_localities_muni', table_name='localities')
    op.drop_geospatial_index('idx_localities_boundary', table_name='localities', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('localities')
    op.drop_index('idx_technologies_type', table_name='technologies')
    op.drop_table('technologies')
    op.drop_geospatial_index('idx_service_zones_polygon', table_name='service_zones', postgresql_using='gist', column_name='polygon')
    op.drop_geospatial_table('service_zones')
    op.drop_index('idx_municipalities_county', table_name='municipalities')
    op.drop_table('municipalities')
    op.drop_index('idx_bulk_operations_user', table_name='bulk_operations')
    op.drop_index('idx_bulk_operations_created', table_name='bulk_operations')
    op.drop_table('bulk_operations')
    op.drop_index('idx_audit_log_user', table_name='audit_log')
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    op.drop_index('idx_audit_log_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('technology_types')
    op.drop_table('counties')
    # ### end Alembic commands ###

    op.drop_index('idx_api_keys_user', table_name='api_keys')
    op.drop_index('idx_addresses_locality', table_name='addresses')
    op.drop_index('idx_addresses_street', table_name='addresses')
    op.drop_index('idx_addresses_house_no_trgm', table_name='addresses')
    op.drop_index('idx_streets_full_name_trgm', table_name='streets')
    op.drop_index('idx_localities_name_trgm', table_name='localities')
    op.execute("DROP EXTENSION IF EXISTS unaccent")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    op.execute("DROP EXTENSION IF EXISTS postgis CASCADE")
